// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDDBgnRfWojHPHdnDoEgquDQaOANvYvmw',
    appId: '1:388505700465:web:123a06d1ea399b58d973d0',
    messagingSenderId: '388505700465',
    projectId: 'urbanculture-63087',
    authDomain: 'urbanculture-63087.firebaseapp.com',
    storageBucket: 'urbanculture-63087.appspot.com',
    measurementId: 'G-X23MDWR6G4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA9yP6jMAv6fyKG2w1DrJKoqRVP6UUvJo',
    appId: '1:388505700465:android:82f3837d5aef5118d973d0',
    messagingSenderId: '388505700465',
    projectId: 'urbanculture-63087',
    storageBucket: 'urbanculture-63087.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7TT8a1_D-mZrD19ixN-n-TuEYPEiRF2k',
    appId: '1:388505700465:ios:4f8717a15eb9bf5bd973d0',
    messagingSenderId: '388505700465',
    projectId: 'urbanculture-63087',
    storageBucket: 'urbanculture-63087.appspot.com',
    iosBundleId: 'com.example.urbanCulture',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7TT8a1_D-mZrD19ixN-n-TuEYPEiRF2k',
    appId: '1:388505700465:ios:14e0b23977f26e36d973d0',
    messagingSenderId: '388505700465',
    projectId: 'urbanculture-63087',
    storageBucket: 'urbanculture-63087.appspot.com',
    iosBundleId: 'com.example.urbanCulture.RunnerTests',
  );
}
